In [1]:
import pandas as pd 
import numpy as np

In [14]:
df = pd.read_csv('/kaggle/input/pokemon1/Pokemon.csv')

In [15]:
df.head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

In [16]:
df['HP']

0      45
1      60
2      80
3      80
4      39
       ..
795    50
796    50
797    80
798    80
799    80
Name: HP, Length: 800, dtype: int64

In [17]:
df.columns

Index(['#', 'Name', 'Type 1', 'Type 2', 'Total', 'HP', 'Attack', 'Defense',
       'Sp. Atk', 'Sp. Def', 'Speed', 'Generation', 'Legendary'],
      dtype='object')

In [18]:
df[['Name', 'Type 1', 'HP']]

                      Name   Type 1  HP
0                Bulbasaur    Grass  45
1                  Ivysaur    Grass  60
2                 Venusaur    Grass  80
3    VenusaurMega Venusaur    Grass  80
4               Charmander     Fire  39
..                     ...      ...  ..
795                Diancie     Rock  50
796    DiancieMega Diancie     Rock  50
797    HoopaHoopa Confined  Psychic  80
798     HoopaHoopa Unbound  Psychic  80
799              Volcanion     Fire  80

[800 rows x 3 columns]

In [22]:
df.iloc[2,1]

'Venusaur'

In [23]:
df.iloc[1:4]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False

In [24]:
df.iloc[0:4]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False

In [29]:
#for index, row in df.iterrows():
 #   print(index,row)

In [31]:
#for index, row in df.iterrows():
  #  print(index,row['Name'])

In [66]:
#df.loc[df['Type 1'] == 'Fire']

In [ ]:
#df.loc[df['Type 1'] == 'Grass']

In [36]:
df.describe()

,#,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
count,800.000000,800.00000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.00000
mean,362.813750,435.10250,69.258750,79.001250,73.842500,72.820000,71.902500,68.277500,3.32375
std,208.343798,119.96304,25.534669,32.457366,31.183501,32.722294,27.828916,29.060474,1.66129
min,1.000000,180.00000,1.000000,5.000000,5.000000,10.000000,20.000000,5.000000,1.00000
25%,184.750000,330.00000,50.000000,55.000000,50.000000,49.750000,50.000000,45.000000,2.00000
50%,364.500000,450.00000,65.000000,75.000000,70.000000,65.000000,70.000000,65.000000,3.00000
75%,539.250000,515.00000,80.000000,100.000000,90.000000,95.000000,90.000000,90.000000,5.00000
max,721.000000,780.00000,255.000000,190.000000,230.000000,194.000000,230.000000,180.000000,6.00000

In [38]:
df.sort_values('Name')

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
510,460,Abomasnow,Grass,Ice,494,90,92,75,92,85,60,4,False
511,460,AbomasnowMega Abomasnow,Grass,Ice,594,90,132,105,132,105,30,4,False
68,63,Abra,Psychic,NaN,310,25,20,15,105,55,90,1,False
392,359,Absol,Dark,NaN,465,65,130,60,75,60,75,3,False
393,359,AbsolMega Absol,Dark,NaN,565,65,150,60,115,60,115,3,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
632,571,Zoroark,Dark,NaN,510,60,105,60,120,60,105,5,False
631,570,Zorua,Dark,NaN,330,40,65,40,80,40,65,5,False
46,41,Zubat,Poison,Flying,245,40,45,35,30,40,55,1,False
695,634,Zweilous,Dark,Dragon,420,72,85,70,65,70,58,5,False
794,718,Zygarde50% Forme,Dragon,Ground,600,108,100,121,81,95,95,6,True

In [45]:
#df.sort_values('Name', ascending=False)

In [44]:
#df.sort_values(['Name', 'HP'])

In [43]:
df.sort_values(['Name', 'HP'], ascending=False)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
794,718,Zygarde50% Forme,Dragon,Ground,600,108,100,121,81,95,95,6,True
695,634,Zweilous,Dark,Dragon,420,72,85,70,65,70,58,5,False
46,41,Zubat,Poison,Flying,245,40,45,35,30,40,55,1,False
631,570,Zorua,Dark,NaN,330,40,65,40,80,40,65,5,False
632,571,Zoroark,Dark,NaN,510,60,105,60,120,60,105,5,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
393,359,AbsolMega Absol,Dark,NaN,565,65,150,60,115,60,115,3,False
392,359,Absol,Dark,NaN,465,65,130,60,75,60,75,3,False
68,63,Abra,Psychic,NaN,310,25,20,15,105,55,90,1,False
511,460,AbomasnowMega Abomasnow,Grass,Ice,594,90,132,105,132,105,30,4,False
510,460,Abomasnow,Grass,Ice,494,90,92,75,92,85,60,4,False

In [ ]:
#adding column

In [ ]:
#Long Method This is Too Long 
#df['Total'] = df['HP'] + df['Attack'] + df['Defense'] + df['Sp. Atk'] + df['Sp. Def'] + df['Speed']

# df = df.drop(columns=['Total'])

In [55]:
df['Total'] = df.iloc[:,5:11].sum(axis=1)
df.head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

In [54]:
45+49+49+65+65+45

318

In [58]:
cols = list(df.columns.values)
cols

['#',
 'Name',
 'Type 1',
 'Type 2',
 'Total',
 'HP',
 'Attack',
 'Defense',
 'Sp. Atk',
 'Sp. Def',
 'Speed',
 'Generation',
 'Legendary']

In [62]:
#save
#df.to_csv('modified.csv', index=False)

In [63]:
#Filter 
new_df = df.loc[(df['Type 1'] == 'Grass') & (df['Type 2'] == 'Poison') & (df['HP']>70)]
new_df

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
50,45,Vileplume,Grass,Poison,490,75,80,85,110,90,50,1,False
77,71,Victreebel,Grass,Poison,490,80,105,65,100,70,70,1,False
652,591,Amoonguss,Grass,Poison,464,114,85,70,85,80,30,5,False

In [67]:
df.loc[df['Name'].str.contains('Mega')]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,count
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,1
7,6,CharizardMega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False,1
8,6,CharizardMega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False,1
12,9,BlastoiseMega Blastoise,Water,NaN,630,79,103,120,135,115,78,1,False,1
19,15,BeedrillMega Beedrill,Bug,Poison,495,65,150,40,15,80,145,1,False,1
23,18,PidgeotMega Pidgeot,Normal,Flying,579,83,80,80,135,80,121,1,False,1
71,65,AlakazamMega Alakazam,Psychic,NaN,590,55,50,65,175,95,150,1,False,1
87,80,SlowbroMega Slowbro,Water,Psychic,590,95,75,180,130,80,30,1,False,1
102,94,GengarMega Gengar,Ghost,Poison,600,60,65,80,170,95,130,1,False,1
124,115,KangaskhanMega Kangaskhan,Normal,NaN,590,105,125,100,60,100,100,1,False,1
137,127,PinsirMega Pinsir,Bug,Flying,600,65,155,120,65,90,105,1,False,1
141,130,GyaradosMega Gyarados,Water,Dark,640,95,155,109,70,130,81,1,False,1
154,142,AerodactylMega Aerodactyl,Rock,Flying,615,80,135,85,70,95,150,1,False,1
163,150,MewtwoMega Mewtwo X,Psychic,Fighting,780,106,190,100,154,100,130,1,True,1
164,150,MewtwoMega Mewtwo Y,Psychic,NaN,780,106,150,70,194,120,140,1,True,1
168,154,Meganium,Grass,NaN,525,80,82,100,83,100,80,2,False,1
196,181,AmpharosMega Ampharos,Electric,Dragon,610,90,95,105,165,110,45,2,False,1
224,208,SteelixMega Steelix,Steel,Ground,610,75,125,230,55,95,30,2,False,1
229,212,ScizorMega Scizor,Bug,Steel,600,70,150,140,65,100,75,2,False,1
232,214,HeracrossMega Heracross,Bug,Fighting,600,80,185,115,40,105,75,2,False,1
248,229,HoundoomMega Houndoom,Dark,Fire,600,75,90,90,140,90,115,2,False,1
268,248,TyranitarMega Tyranitar,Rock,Dark,700,100,164,150,95,120,71,2,False,1
275,254,SceptileMega Sceptile,Grass,Dragon,630,70,110,75,145,85,145,3,False,1
279,257,BlazikenMega Blaziken,Fire,Fighting,630,80,160,80,130,80,100,3,False,1
283,260,SwampertMega Swampert,Water,Ground,635,100,150,110,95,110,70,3,False,1
306,282,GardevoirMega Gardevoir,Psychic,Fairy,618,68,85,65,165,135,100,3,False,1
327,302,SableyeMega Sableye,Dark,Ghost,480,50,85,125,85,115,20,3,False,1
329,303,MawileMega Mawile,Steel,Fairy,480,50,105,125,55,95,50,3,False,1
333,306,AggronMega Aggron,Steel,NaN,630,70,140,230,60,80,50,3,False,1
336,308,MedichamMega Medicham,Fighting,Psychic,510,60,100,85,80,85,100,3,False,1
339,310,ManectricMega Manectric,Electric,NaN,575,70,75,80,135,80,135,3,False,1
349,319,SharpedoMega Sharpedo,Water,Dark,560,70,140,70,110,65,105,3,False,1
354,323,CameruptMega Camerupt,Fire,Ground,560,70,120,100,145,105,20,3,False,1
366,334,AltariaMega Altaria,Dragon,Fairy,590,75,110,110,110,105,80,3,False,1
387,354,BanetteMega Banette,Ghost,NaN,555,64,165,75,93,83,75,3,False,1
393,359,AbsolMega Absol,Dark,NaN,565,65,150,60,115,60,115,3,False,1
397,362,GlalieMega Glalie,Ice,NaN,580,80,120,80,120,80,100,3,False,1
409,373,SalamenceMega Salamence,Dragon,Flying,700,95,145,130,120,90,120,3,False,1
413,376,MetagrossMega Metagross,Steel,Psychic,700,80,145,150,105,110,110,3,False,1
418,380,LatiasMega Latias,Dragon,Psychic,700,80,100,120,140,150,110,3,True,1
420,381,LatiosMega Latios,Dragon,Psychic,700,80,130,100,160,120,110,3,True,1
426,384,RayquazaMega Rayquaza,Dragon,Flying,780,105,180,100,180,100,115,3,True,1
476,428,LopunnyMega Lopunny,Normal,Fighting,580,65,136,94,54,96,135,4,False,1
494,445,GarchompMega Garchomp,Dragon,Ground,700,108,170,115,120,95,92,4,False,1
498,448,LucarioMega Lucario,Fighting,Steel,625,70,145,88,140,70,112,4,False,1
511,460,AbomasnowMega Abomasnow,Grass,Ice,594,90,132,105,132,105,30,4,False,1
527,475,GalladeMega Gallade,Psychic,Fighting,618,68,165,95,65,115,110,4,False,1
591,531,AudinoMega Audino,Normal,Fairy,545,103,60,126,80,126,50,5,False,1
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True,1

In [ ]:
#Aggregate

In [65]:
df['count'] = 1
df.groupby(['Type 1', 'Type 2']).count()['count']

Type 1  Type 2
Bug     Electric     2
        Fighting     2
        Fire         2
        Flying      14
        Ghost        1
                    ..
Water   Ice          3
        Poison       3
        Psychic      5
        Rock         4
        Steel        1
Name: count, Length: 136, dtype: int64